apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 
  namespace: argocd-sha
spec:
  project: default

  source:
    repoURL: 
    targetRevision: HEAD
    path: main
  destination: 
    server: https://kubernetes.default.svc
    namespace: 

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
