apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd-build
spec:
  project: default

  source:
    repoURL: git@github.com:skhossain117/argocd-pipeline.git
    targetRevision: HEAD
    path: main
  destination: 
    server: https://172.31.26.12:6443
    namespace: argocd-build

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
